### ISSUE TITLE
Не меняется текст кнопки Upload

### ISSUE THREAD

**Issue by aska-kps** [floor12/yii2-module-files#10]
Если передать uploadButtonText в field,то текст не меняется.Так как он строго задан при init в FileInputWidget.php;

`<?= $form->field($model, 'passport')->widget(\floor12\files\components\FileInputWidget::class,[
                    'uploadButtonText' => 'asd'
]) ?>`

`public function init()
    {
        $this->registerTranslations();
        $this->block_id = rand(9999999, 999999999);
        $this->uploadButtonText = Yii::t('files', 'Upload');`

**Comment by floor12** [comment]
this bug is fixed in master branch. you can try  to use dev-master version in your composer or wait a little to release.

```php
    public function init()
    {
        $this->registerTranslations();
        $this->block_id = rand(9999999, 999999999);

        if (!$this->uploadButtonText)
            $this->uploadButtonText = Yii::t('files', 'Upload');
```
