### ISSUE TITLE
Reflection Exception. Class does not exist

### ISSUE THREAD

**Issue by aska-kps** [floor12/yii2-module-files#11]
После сабмита формы с изображением сразу выдает ошибку.
Однако изображение все равно загружается.

![Снимок экрана 2021-06-17 150627](https://user-images.githubusercontent.com/54268522/122366829-ba656180-cf7d-11eb-9199-f19e4ba3fdbc.png)

Если изменить в файле \vendor\floor12\yii2-module-files\src\views\default\_single.php :
(20ая строка)
`if (is_array($model))
    $model = $model[0];`
На `if (is_array($model))
    $model = $model[1];`
    
    То ошибок нет и все работает.

**Comment by floor12** [comment]
Посмотрю. Так просто менять не стоит, могут отвалиться другие случаи... )

**Comment by aska-kps** [comment]
Обновился, работает. Благодарю
