### ISSUE TITLE
How to handle saving?

### ISSUE THREAD

**Issue by ghost** [floor12/yii2-module-files#2]
I am trying the module, it uploads image to storage folder, it saves the image to its "file" table, but I do not see it saves anything on my table. I tried adding image listing widget to see if it was able to read the image saved, but no luck.

Also for multiple images what kind of db field do I need to create? or do I need to create a separate table?

**Comment by ghost** [comment]
I found the issue, the field does not have to exist in database, since it is calling magic method _get to bring data from "file" table.

**Comment by floor12** [comment]
Hello. All data stored in one database table 'file'.  This table contents name of AR model, its ID and field name. 
After adding file to form, it already added in database with object_id=0, after saving active record model the file record updates with at id.

**Comment by ghost** [comment]
Yes, I understood that. I was having issues because when editing or listing image was not being shown. The issue was I was using a real database field, so __get method in the behavior didn't trigger.

**Comment by mtangoo** [comment]
I'm struggling to understand this too. I have everything set and the information is correctly saved in the files table. But I still cannot load it. The field is always null instead of file object.

@ghost, can you provide an example of how you did it? I seem to miss something!

**Comment by juppwerner** [comment]
Have you been able to solve the issue?
I have the same problem. The file gets uploaded but the object-id stays 0, so the file is not shown in the list widget.

**Comment by floor12** [comment]
I dont know how to help. I use this module in a lot of project and have not any issues. This module will work only in unix-like OS. If you are trying to use it in windows host, probably that is a problem.

**Comment by juppwerner** [comment]
I am using it in 2 different projects, running on WSL /Docker. In one project, uploaded files get attached to the owner object, in th e other project they don't.
I am still trying to find out why.

**Comment by juppwerner** [comment]
I am sorry the problem was I had an own afterSave method in my ActiveRecord, where I forgot to call parent::afterSave().
So the FIleBehavior event could not get triggered.
Sorry for bothering ...
