### ISSUE TITLE
Проблема при загрузке 1 файла

### ISSUE THREAD

**Issue by jsalex** [floor12/yii2-module-files#4]
При загрузке 1 файла (при первой) выдает такую ошибку:

<img width="393" alt="Скриншот 2020-06-15 15 56 04" src="https://user-images.githubusercontent.com/13667938/84666012-d8d6ee00-af20-11ea-9a45-2d111afba96a.png">

Связано с тем что при обращение на адрес загрузки вылетает 400 ошибка - как будто одиночный файл не загружает.

При загрузке 2 и более файлов вылетает вот так

<img width="383" alt="Скриншот 2020-06-15 16 00 27" src="https://user-images.githubusercontent.com/13667938/84666445-5ef33480-af21-11ea-98f2-c7ec578f0392.png">

**Comment by floor12** [comment]
Нужно в консоли посмотри 400я ошибка с каким именно текстом, или посмотреть в логах. Хотя я примерно представляю что это может быть... У меня на всех проектах работает вроде бы стабильно. Нужно больше информации, какая версия yii, php. и прочего окружения, которое может повлиять.

**Comment by jsalex** [comment]
Версия уii 2.0.35
PHP Version 7.2.26

`Failed to load resource: Сетевое соединение потеряно. `

`https://site.ru/admin/files/default/upload`

**Comment by floor12** [comment]
Смотри, скорее всего там проблема с редиректом может быть или путями. По идее модуль должен иметь свои служебные разделы `/files/default/upload` без префиксов, может быть где-то с этим проблема. Ведь модуль регистрирует свои контроллеры как контроллеры отдельного модуля files, и, если специально не менять их. urlManager, то приставки `admin` там не должно быть...

**Comment by jsalex** [comment]
Это получается advanced версия и в конфиге admin определен baseUrl
```
       'request' => [
                             'baseUrl' => '/admin',
        ],
```

**Comment by jsalex** [comment]
Еще момент 2 файл начинает нормально грузить - 1 пропускает и эту ошибку выкидывает

**Comment by floor12** [comment]
А посмотри по логу запросов из браузера в момент загрузки какие запросу идут и куда. И какие там коды ответов на каждый запрос на загрузку файла, особенно на первый. Может на нем происходит редирект от сервера и остальные запросы идут уже правильный... Интересный кейс, я никогда не использовал backend приложение в отдельной папке, я всегда вешал его на поддомен.

**Comment by jsalex** [comment]
Так по консоли yii2 вижу следующее
 
<img width="441" alt="Скриншот 2020-06-16 23 20 46" src="https://user-images.githubusercontent.com/13667938/84829423-0a86ac80-b028-11ea-947b-76be06bb6d40.png">

**Comment by jsalex** [comment]
Хм, сейчас залез в логи nginx отловил ошибку - завтра дам знать точнее
`client intended to send too large body: **** bytes, request: "POST"`

**Comment by floor12** [comment]
По этой ошибке могу посоветовать поставить `client_max_body_size 5000m;` для установки 5гб, примеру. Может там слишком большой файл тестовый?

**Comment by floor12** [comment]
Так как ответов нет, закрываю тикет.
