### ISSUE TITLE
Проблема при загрузке файла 404

### ISSUE THREAD

**Issue by prox3000** [floor12/yii2-module-files#5]
https://prnt.sc/tofwte

**Comment by prox3000** [comment]
Вот что уставновлено в config.php

'modules' => [
		'files' => [
			'class' => 'floor12\files\Module',
			'storage' => dirname(__DIR__).'/web/files/cache',
			'cache' => dirname(__DIR__).'/web/files/storage',
			'token_salt' => 'asdlkfjdsfAdib',
		],
    ],

**Comment by prox3000** [comment]
Думаю проблема с роутингом  у меня прописано так 
 'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
                '' => 'site/index',
                '<controller:\w+>/<action:\w+>/<id:\w+>' => '<controller>/<action>',
				'<module:\w+>/<controller:w+>/<action:\w+>/<id:\w+>' => '<module>/<controller>/<action>',
            ],
        ],

**Comment by floor12** [comment]
Я давно сюда не заходил. Видимо, проблема не актуальна )
