### ISSUE TITLE
Проблема в миграции при начилии префиксов

### ISSUE THREAD

**Issue by aska-kps** [floor12/yii2-module-files#8]
Если использовать tablePrefix, то при выполнении миграции yii migrate --migrationPath=@vendor/floor12/yii2-module-files/src/migrations/ выдает ошибку.Так как во второй миграции 'ater_file' таблица указана без {{%sometable}}.И таблица с префиксом не найдена.

**Comment by floor12** [comment]
Понял, поправил. Скоро сделаю релиз с багфиксами.
